### ISSUE TITLE
大佬请问如何和你取得联系

### ISSUE THREAD

**Issue by tongmingxuan** [Jamlee/swoft-tars#3]
大佬请问如何和你取得联系 我是刚用tars  当部署了这个代码之后  运行几秒钟 他就会被kill掉  我不知道是什么原因 希望可以请教你一下

**Comment by Jamlee** [comment]
这个项目我只是根据网上的资料，用了一下试试。可能项目有点老了

**Comment by tongmingxuan** [comment]
大佬  我如果通过 php index.php启动 或者 tars自己运行他   他会在启动之后就停止运行   但是 如果我是php bin/swoft http:start /http:restart 这种运行 他就不会停止

**Comment by tongmingxuan** [comment]
他这个 tars 这个东西我文档看不太明白。。。。。我也不知道 他为什么会一直给index.php发送stop 这种请求

**Comment by Jamlee** [comment]
因为 tars 启动 停止 程序都是给 进程发消息。tars 把我们的程序包解压 放到某个目录。 然后启动 php 。当然tars是不是有个健康检查 ，会检查php服务的某个端口，不通就会发stop然后重启？

**Comment by tongmingxuan** [comment]
大佬请问你在swoft里面设置的健康检查端口是在哪里配置的    tats会定时访问这个swoft开放的端口吗  那我应该如何设置这个swoft的这个端口

**Comment by Jamlee** [comment]
应该在你发布 tar 包时填写的某个端口 你看看哪个像 我手头上没有tar的环境

**Comment by tongmingxuan** [comment]
发布tar包的时候确实填写端口了  但是内个是tars master访问server的端口  并不是健康检查的端口啊

**Comment by Jamlee** [comment]
加我微信 一起看看 jam13579

**Comment by tongmingxuan** [comment]
好的 大佬 我已经添加你得微信了
